fix exit issue

diff --git a/.github/workflows/pre-release.yml b/.github/workflows/pre-release.yml
--- a/.github/workflows/pre-release.yml
+++ b/.github/workflows/pre-release.yml
@@ -111,7 +111,10 @@ jobs:
       - name: Exit
         id: exit
         run: |
-          if [ "${{ steps.check.outputs.release_name_check }}" == "false"] || ["${{steps.check-release-name.outputs.need_release }}" == "true"]; then
+          if ["${{steps.check-release-name.outputs.need_release }}" == "false"]; then
+            echo "::error::Release name check failed."
+            exit 1
+          else if [ "${{ steps.check.outputs.release_name_check }}" == "false"]; then
             echo "::error::Release name check failed."
             exit 1
           else
